### ISSUE TITLE
global elastic search option

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-ft-api-client#16]
so e.g. `.configure({
   elasticSearch: flags.get('elasticSearch')
})`

makes elastic search the default for all endpoints

**Comment by matthew-andrews** [comment]
Going to say no for now…… I found myself unable to use Elastic Search quite often so would prefer to explicitly opt in wherever appropriate and don't really want the complexity of having to check in two places before making this sort of decision.

Also because flags can be set on a per-request basis I'm not sure this would even work……  Whilst one request was mid being processed the second request could change this value and affect the first……

**Comment by matthew-andrews** [comment]
examples of unable to use elastic
https://github.com/Financial-Times/next-dobi/blob/master/server/controllers/stream.js#L63
https://github.com/Financial-Times/next-grumman/blob/master/server/controllers/capi.js#L165
